site_name: CRXN
theme: readthedocs

nav:
   - Home: index.md
   - Getting started:
      - Guide: getting-started.md
      - Rules: rules.md
      - Requirements: requirements.md
      - Registration:
         - Registering and adding your prefix to EntityDB: registration/entitydb.md
      - Network configuration: network/setup.md
      - Routing:
         - Setting up Bird: routing/bird/bird.md
            - Bird configuration: 
      - Tunneling:
         - Fastd: tunneling/fastd.md
      - Setting up your home network:
         - Configuring your hosts:
            - Automatically with SLAAC and radv:
               - Setting up radv (router): radv.md
               - Setting up SLAAC (hosts): slaac/slaac.md
         - CRXN DNS: dns/dns.md
      - Using the network: usage/
   - Additional:
      - On-the-go CRXN:
         - What is it?: otg/index.md
         - Deavmi's OTG: otg/deavmi.md
         - Rany's OTG: otg/rany.md
   - Peers: peers.md
   - Services: services.md
   - People: people/people.md