site_name: CRXN
theme: yeti

nav:
  - Home: index.md
  - Getting started:
      - Guide: getting-started.md
      - Rules: rules.md
      - Requirements: requirements.md
      - Assigning subnet: prefixes.md
      - Routing:
         - Introduction: routing.md
         - Bird-based routing:
            - Basics: bird_basics.md
            - Configuration: bird_config.md
         - Babeld-based routing
         - Mikrotik-based routing
  - Tutorial:
      - Peering: peering.md
      - CRXNv6: crxnv6.md
      - On-the-go: onthego.md
      - Configs:
        - Bird: configs/bird.md
  - Peers: peers.md
  - Services: services.md
  - Registrar: ipam.md
  - People: peopel.md
