site_name: CRXN
theme: yeti

nav:
  - Home: index.md
  - Tutorial:
      - Peering: peering.md
      - CRXNv6: crxnv6.md
      - On-the-go: onthego.md
  - Peers: peers.md
  - Services: services.md
  - Registrar: ipam.md
