site_name: CRXN
theme: readthedocs

nav:
   - Home: index.md
   - Getting started:
      - Guide: getting-started.md
      - Rules: rules.md
      - Requirements: requirements.md
      - Registration:
         - Registering a new /48 ULA: register_ula.md
         - Adding your prefix to EntityDB: entitydb.md
      - Routing:
         - Setting up Bird:
            - Bird basics: bird_basics.md
            - Bird configuration:
               - Bird 1.6: bird1.6.md
               - Bird 2: bird2.md
            - Protocols:
               - Babel: bird_babel.md
               - OSPFv3: bird_ospfv3.md
      - Additional:
         - On-the-go: onthego.md
   - Peers: peers.md
   - Services: services.md
   - People: people.md