site_name: CRXN
theme: yeti

nav:
  - Home: index.md
  - Network:
    - Tutorial:
      - Peering: peering.md
      - CRXNv6: crxnv6.md
    - Nodes: peers.md
    - Services: services.md
    - Registrar: ipam.md
